// Sample comments for the demo — mix of real-sounding comments
// In production these come from the regulations.gov API
export const REAL_COMMENTS = [
  "As a small business owner in rural Ohio, I depend on an open internet to reach my customers.",
  "Net neutrality ensures that ISPs cannot prioritize their own content over competitors.",
  "I am a teacher and rely on equal access to educational resources online.",
  "Please protect net neutrality. My startup cannot afford to pay for fast lanes.",
  "The internet should remain a level playing field for all Americans.",
  "I work from home and need reliable, unthrottled internet access for my livelihood.",
  "Without net neutrality, large corporations will control what we can access online.",
  "As a veteran, I rely on telehealth services that require open internet access.",
  "Net neutrality is essential for free speech and democratic participation.",
  "I'm a college student who can't afford to pay more for the sites I need for research.",
  "Rural communities like mine will suffer most without net neutrality protections.",
  "The FCC should protect consumers, not cable company profits.",
  "An open internet drives innovation and economic growth across all sectors.",
  "My disabled son relies on assistive technologies that require equal bandwidth access.",
  "Please don't let ISPs create a two-tiered internet that favors the wealthy.",
  "As a nurse practitioner, I need unrestricted access to medical databases.",
  "Net neutrality is not a partisan issue — it affects every American equally.",
  "Small online retailers like mine cannot survive in a pay-to-play internet.",
  "I run a nonprofit that serves low-income families — we need open internet access.",
  "The proposed changes will stifle competition and harm consumers.",
  "My children deserve the same internet access as children of wealthy families.",
  "As an independent journalist, net neutrality protects my ability to publish freely.",
  "Internet service should be treated as a utility, not a luxury product.",
  "I'm a software developer and open internet is the foundation of my entire industry.",
  "Removing net neutrality will allow ISPs to pick winners and losers online.",
  "I live in a rural area with only one ISP option — I have no choice if they throttle.",
  "Net neutrality protects the next generation of entrepreneurs and innovators.",
  "As a librarian, I believe everyone deserves equal access to information online.",
  "The internet has become essential infrastructure — it must remain open.",
  "Please consider the millions of Americans who depend on a free and open internet.",
];

export const FAKE_COMMENTS = [
  "The current regulatory framework is outdated and stifles broadband investment.",
  "Removing Title II classification will encourage infrastructure development.",
  "The free market, not government regulation, should determine internet policy.",
  "Excessive regulation has hindered broadband deployment in underserved areas.",
  "I support the FCC's proposal to restore internet freedom and reduce regulation.",
  "Title II regulations impose unnecessary burdens on internet service providers.",
  "Deregulation will lead to increased competition and lower prices for consumers.",
  "The 2015 rules were a solution in search of a problem that didn't exist.",
  "Government should not be in the business of regulating the internet.",
  "Light-touch regulation has historically produced the best outcomes for consumers.",
  "The current rules discourage the investment needed to expand rural broadband.",
  "I believe in free market principles and oppose heavy-handed internet regulation.",
  "Restoring internet freedom will promote innovation and consumer choice.",
  "The FCC should focus on bridging the digital divide, not regulating ISPs.",
  "Title II classification treats the internet like a 1930s telephone monopoly.",
  "I support Chairman Pai's proposal to modernize internet regulation.",
  "Broadband providers should be free to manage their networks efficiently.",
  "The previous administration's internet regulations were government overreach.",
  "Competition, not regulation, is the best way to protect consumers online.",
  "The proposed changes will unleash investment and create jobs in the tech sector.",
  "Overregulation of the internet threatens American technological leadership.",
  "I urge the FCC to repeal the burdensome Title II internet regulations.",
  "Market-based solutions are preferable to government mandates for internet policy.",
  "The 2015 net neutrality rules were adopted through a flawed rulemaking process.",
  "Reducing regulatory barriers will accelerate 5G deployment across the country.",
  "I support rolling back regulations that have slowed broadband infrastructure investment.",
  "The internet thrived for decades without Title II regulation.",
  "Heavy regulation discourages the private investment needed for better internet service.",
  "The FCC should return to the bipartisan light-touch framework that worked.",
  "I support the Restoring Internet Freedom proposal as written.",
  "Government regulation of the internet sets a dangerous precedent for free speech.",
  "The proposed rule correctly identifies that Title II has harmed network investment.",
  "American consumers deserve more choices, not more government control of the internet.",
  "ISPs need regulatory certainty to justify billions in infrastructure spending.",
  "The current regulations create legal uncertainty that chills broadband investment.",
  "I believe the FCC should restore the regulatory framework that fostered internet growth.",
  "Title II imposes costs that are ultimately passed on to consumers.",
  "The internet economy grew because of freedom from regulation, not because of it.",
  "Rolling back these rules will benefit consumers through better service and lower prices.",
  "I strongly support the FCC's proposal to restore internet freedom.",
];

export function getRandomComment(fake: boolean): string {
  const pool = fake ? FAKE_COMMENTS : REAL_COMMENTS;
  return pool[Math.floor(Math.random() * pool.length)];
}
